version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  bot-api:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  frontend:
    executor:
      name: node/default
    working_directory: ~/sentry/frontend
    steps:
      - checkout:
          path: ~/sentry
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    test:
      frontend-api:
        - bot-api
        - frontend
